# Generated by Django 4.2.3 on 2023-07-11 12:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=2083, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=150, null=True)),
                ('stars', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('availability', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
